### ISSUE TITLE
Type Juggling

### ISSUE THREAD

**Issue by zombozo12** [ichwanulf99/vigenere-cipher#1]
https://github.com/ichwanulfadhli/vigenere-cipher/blob/92b4d9ad11ab94de4d4d828ec08f8712d7f8e6d7/Vigenere.php#L44

PHP punya fitur namaya PHP Type Juggling, biasanya digunakan saat menggunakan penkondisian seperti if else dll. PHP akan mengkonversi value ke _comparable type_.

Variable `$key` jika memiliki _value_ `0`, `false`, `array()`, dan "" (empty string) menggunakan operator `==` di dalam pengkondisian `IF ELSE`, maka `$key` akan dianggap sebagai `NULL`.
Contoh: 
`0 == NULL` adalah `true`
`array() == NULL` adalah `true` karena `array()` sebagai default tidak memiliki isi akan ter-define sebagai `NULL`.
Untuk menghindari kejadian yang seharusnya tidak terjadi, dan apabila _value_ yang diinginkan hanyalah `NULL`, maka saya sarankan menggunakan operator `===` agar proses perbandingan dapat lebih _strict_.

References:
[PHP Type Juggling by Chris Smith](https://www.owasp.org/images/6/6b/PHPMagicTricks-TypeJuggling.pdf)
[PHP.net](https://www.php.net/manual/en/types.comparisons.php)
[PHP Type Juggling Vulnerabilities](https://medium.com/swlh/php-type-juggling-vulnerabilities-3e28c4ed5c09)

**Comment by ichwanulfadhli** [comment]
> https://github.com/ichwanulfadhli/vigenere-cipher/blob/92b4d9ad11ab94de4d4d828ec08f8712d7f8e6d7/Vigenere.php#L44
> 
> PHP punya fitur namaya PHP Type Juggling, biasanya digunakan saat menggunakan penkondisian seperti if else dll. PHP akan mengkonversi value ke _comparable type_.
> 
> Variable `$key` jika memiliki _value_ `0`, `false`, `array()`, dan "" (empty string) menggunakan operator `==` di dalam pengkondisian `IF ELSE`, maka `$key` akan dianggap sebagai `NULL`.
> Contoh:
> `0 == NULL` adalah `true`
> `array() == NULL` adalah `true` karena `array()` sebagai default tidak memiliki isi akan ter-define sebagai `NULL`.
> Untuk menghindari kejadian yang seharusnya tidak terjadi, dan apabila _value_ yang diinginkan hanyalah `NULL`, maka saya sarankan menggunakan operator `===` agar proses perbandingan dapat lebih _strict_.
> 
> References:
> [PHP Type Juggling by Chris Smith](https://www.owasp.org/images/6/6b/PHPMagicTricks-TypeJuggling.pdf)
> [PHP.net](https://www.php.net/manual/en/types.comparisons.php)
> [PHP Type Juggling Vulnerabilities](https://medium.com/swlh/php-type-juggling-vulnerabilities-3e28c4ed5c09)

Noted. Makasih ram infonya, btw feel free to contribute!

**Comment by zombozo12** [comment]
Dengan senang hati wa

**Comment by ichwanulfadhli** [comment]
> Dengan senang hati wa

Berarti gua hanya perlu mengganti "==" dengan "===", gitu?
Jadinya gini? 
```
if(empty($key) || $key === NULL){ 
```
